### ISSUE TITLE
Quarterly Themes for Projects to highlight on the homepage

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-gatsby#589]
## 📋 Anything to add?
Create curated themes for projects like on Earth Day create a list of projects with environmental impact. 
Like Netflix style.

More complex algorhythms like the NetFlix style, this would be a mid-term improvement or simpler UI solution for the long-term TOKEN dynamic that will create our end goal curation solution.

## 🎉 Subtasks

- [x] Create a list of all themes 
- [ ] Design banners/graphics to promote the themed bucket
- [ ] UI design on Homepage to promote 
- [ ] Single page of the Theme

## 🤼‍ Reviewer

@WhyldWanderer

**Comment by markoprljic** [comment]
Inspiration 
![Image 2021-03-12 at 5 58 19 pm](https://user-images.githubusercontent.com/5704285/110972689-8f56ea80-835c-11eb-921b-46c23185a687.jpg)

**Comment by WhyldWanderer** [comment]
We could eventually use the project tags to curate some of the themes... although, we might need to start more broad at the beginning, (environmental impact projects, social impact projects, crypto projects, etc.) until we have enough projects on the platform to be able to further define them.

**Comment by markoprljic** [comment]
Got it. Should we start with the following then?

- Environmental impact 
- Social impact
- Blockchain and Crypto

**Comment by Danibelle** [comment]
Great suggestions!

**Comment by Danibelle** [comment]
I had to come back to this because it dawned on me that we are subtly yet foundationally separating humanity from nature again which is not advisable.

I'd like to suggest some small changes for the first three to add more diversity while being a bit more specific with the categorization:

1. Ecology & Agriculture
2. Social Justice & Economy
3. Technology & Innovation

****

We could go straight to slightly more robust version, the 9 Gaia Goals are a synthesis of the United Nations' 17 Sustainable Development Goals:

1. Animal & Plant (Ecology) Protection
2. Rivers & Oceans (Water)
3. Sustainable Agriculture & Nutrition (Farms & Food)
4. Waste Reduction & Recycling Management 
5. Energy & Mobility
6. Industry Transformation
7. Social Justice & Peace
8. Protection of Basic Needs
9. Research & Education

Or go full agenda 2030 with alignment to the UN strategy for this decade:
The 17 sustainable development goals (SDGs) to transform our world:

GOAL 1: No Poverty
GOAL 2: Zero Hunger
GOAL 3: Good Health and Well-being
GOAL 4: Quality Education
GOAL 5: Gender Equality
GOAL 6: Clean Water and Sanitation
GOAL 7: Affordable and Clean Energy
GOAL 8: Decent Work and Economic Growth
GOAL 9: Industry, Innovation and Infrastructure
GOAL 10: Reduced Inequality
GOAL 11: Sustainable Cities and Communities
GOAL 12: Responsible Consumption and Production
GOAL 13: Climate Action
GOAL 14: Life Below Water
GOAL 15: Life on Land
GOAL 16: Peace and Justice Strong Institutions
GOAL 17: Partnerships to achieve the Goal

**Comment by WhyldWanderer** [comment]
This is being managed by comms here https://github.com/Giveth/giveth-planning/issues/1291
